### ISSUE TITLE
No module named yaml

### ISSUE THREAD

**Issue by sirwastl** [croedel/M-TEC-API#2]
Hi Christian.

great idea ant thank's for your effort. Could you just give me an advice.
If I run the script there is an 'error':
<img width="904" alt="mtec_api-error" src="https://github.com/croedel/M-TEC-API/assets/126892600/71cf48d0-e904-49d3-ac06-8410739b8cd3">

Thank's and greetings

**Comment by tim4849** [comment]
Same issue like documented from my side. See issue "setup",

**Comment by croedel** [comment]
Hi, 
the project requires https://pypi.org/project/PyYAML/ to be installed.
Installation can usually be done easily from commandline:
pip install pyyaml
