### ISSUE TITLE
API didn't work anymore

### ISSUE THREAD

**Issue by maik-dmxc** [croedel/M-TEC-API#9]
at 2024-11-15 00:59:56 i can't connect anymore.

`Nov 15 11:24:27 raspberrypi systemd[1]: Started mtec.service - MTEC MQTT.
Nov 15 11:24:27 raspberrypi python3[42200]: [INFO] MTEC_mqtt.py: Starting
Nov 15 11:24:27 raspberrypi python3[42200]: [INFO] MTEC_mqtt.py: MQTT server started
Nov 15 11:24:27 raspberrypi python3[42200]: [INFO] MTEC_mqtt.py: Connected to MQTT broker
Nov 15 11:24:27 raspberrypi python3[42200]: [ERROR] MTECapi.py: Couldn't request REST API: login/manager POST ({'channel': 1, 'email': 'xxxxx.xxxx@xxx>
Nov 15 11:24:27 raspberrypi python3[42200]: [ERROR] MTECapi.py: Login error: {'code': '-1'}
Nov 15 11:24:28 raspberrypi python3[42200]: [ERROR] MTECapi.py: Couldn't request REST API: basePowerStationInfo/getRunningOverview GET (None) Exception H>
Nov 15 11:24:28 raspberrypi python3[42200]: [ERROR] MTECapi.py: Error while retrieving base info: {'code': '-1'}
`

any suggestion?

regards maik

**Comment by croedel** [comment]
It seems that the underlying API of the Web frontend was changes by M-TEC respectively the underlying provider. :-( 
Therefore the M-TEC-API is not working anymore. :-( 
At a first glance, it looks like a major change. I need to see when I find time to work on that.

**Comment by maik-dmxc** [comment]
API works,  ididn't do anything
```

● mtec.service - MTEC MQTT
     Loaded: loaded (/lib/systemd/system/mtec.service; enabled; preset: enabled)
     Active: active (running) since Thu 2024-11-21 14:37:57 CET; 9min ago
   Main PID: 2425 (python3)
      Tasks: 2 (limit: 3908)
        CPU: 3.537s
     CGroup: /system.slice/mtec.service
             └─2425 /usr/bin/python3 /home/pi/M-TEC-API/MTEC_mqtt.py


Nov 21 14:37:57 raspberrypi systemd[1]: Started mtec.service - MTEC MQTT.
Nov 21 14:37:57 raspberrypi python3[2425]: [INFO] MTEC_mqtt.py: Starting
Nov 21 14:37:57 raspberrypi python3[2425]: [INFO] MTEC_mqtt.py: MQTT server started
Nov 21 14:37:57 raspberrypi python3[2425]: [INFO] MTEC_mqtt.py: Connected to MQTT broker
```


regards Maik

**Comment by maik-dmxc** [comment]
Hi,

MTEC got an frontend update today.

regards maik
